copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\platform\junit-platform-launcher\1.10.2\junit-platform-launcher-1.10.2.jar libs
copy /b /y /v %ANDROID_HOME%\platforms\android-31\android.jar libs
rem copy /b /y /v %ANDROID_HOME%\platforms\android-31\data\res libs
rem copy /b /y /v %USERPROFILE%\Projects\appium2_sample_01\target\test-classes libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\aspectj\aspectjrt\1.9.22.1\aspectjrt-1.9.22.1.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\aspectj\aspectjtools\1.9.22.1\aspectjtools-1.9.22.1.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\appium\java-client\9.2.3\java-client-9.2.3.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-api\4.21.0\selenium-api-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\4.21.0\selenium-remote-driver-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\auto\service\auto-service-annotations\1.1.1\auto-service-annotations-1.1.1.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\guava\guava\33.2.0-jre\guava-33.2.0-jre.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\guava\failureaccess\1.0.2\failureaccess-1.0.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\checkerframework\checker-qual\3.42.0\checker-qual-3.42.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\j2objc\j2objc-annotations\3.0.0\j2objc-annotations-3.0.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\semconv\opentelemetry-semconv\1.25.0-alpha\opentelemetry-semconv-1.25.0-alpha.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-api\1.38.0\opentelemetry-api-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-context\1.38.0\opentelemetry-context-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-exporter-logging\1.38.0\opentelemetry-exporter-logging-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk-common\1.38.0\opentelemetry-sdk-common-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure-spi\1.38.0\opentelemetry-sdk-extension-autoconfigure-spi-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk-extension-autoconfigure\1.38.0\opentelemetry-sdk-extension-autoconfigure-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-api-incubator\1.38.0-alpha\opentelemetry-api-incubator-1.38.0-alpha.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk-trace\1.38.0\opentelemetry-sdk-trace-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk\1.38.0\opentelemetry-sdk-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk-metrics\1.38.0\opentelemetry-sdk-metrics-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\io\opentelemetry\opentelemetry-sdk-logs\1.38.0\opentelemetry-sdk-logs-1.38.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\net\bytebuddy\byte-buddy\1.14.15\byte-buddy-1.14.15.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-http\4.21.0\selenium-http-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\dev\failsafe\failsafe\3.3.2\failsafe-3.3.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-json\4.21.0\selenium-json-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-manager\4.21.0\selenium-manager-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-os\4.21.0\selenium-os-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apache\commons\commons-exec\1.4.0\commons-exec-1.4.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\seleniumhq\selenium\selenium-support\4.21.0\selenium-support-4.21.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\code\gson\gson\2.11.0\gson-2.11.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\google\errorprone\error_prone_annotations\2.27.0\error_prone_annotations-2.27.0.jar libs
rem copy /b /y /v %USERPROFILE%\.m2\repository\org\slf4j\slf4j-api\2.0.13\slf4j-api-2.0.13.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\slf4j\slf4j-api\2.0.16\slf4j-api-2.0.16.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\slf4j\slf4j-simple\2.0.16\slf4j-simple-2.0.16.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\jupiter\junit-jupiter\5.10.2\junit-jupiter-5.10.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.10.2\junit-jupiter-api-5.10.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\platform\junit-platform-commons\1.10.2\junit-platform-commons-1.10.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\jupiter\junit-jupiter-params\5.10.2\junit-jupiter-params-5.10.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.10.2\junit-jupiter-engine-5.10.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\junit\platform\junit-platform-engine\1.10.2\junit-platform-engine-1.10.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\com\konghq\unirest-java\3.14.5\unirest-java-3.14.5-standalone.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpcore\4.4.13\httpcore-4.4.13.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpmime\4.5.13\httpmime-4.5.13.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.13\httpcore-nio-4.4.13.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1.5\httpasyncclient-4.1.5.jar libs
copy /b /y /v %USERPROFILE%\.m2\repository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar libs
